### ISSUE TITLE
Incorrectly detects trailing space

### ISSUE THREAD

**Issue by jaymzh** [turboladen/tailor#101]
When using a backslash at the end of a line, it detects the space before the backslash as a trailing newline.

Example, a chef cookbook:

```
execute 'myscript' do
  command \
    '/some/really/long/path/that/would/be/over/eight/chars.sh'
  only_if { something }
end
```

**Comment by turboladen** [comment]
Crap, I thought I fixed that.  Added to 1.0.1 milestone.
