### ISSUE TITLE
tailor should call the same ruby it was called with

### ISSUE THREAD

**Issue by jaymzh** [turboladen/tailor#119]
Tailor currently calls "ruby" in backticks, which calls some random ruby within the path rather than the ruby it was called with which is causes all sorts of bad behavior if you have more than one ruby installed.

**Comment by turboladen** [comment]
Tailor uses `/usr/bin/env ruby`, which should report the proper ruby.  Is there a different way to solve this?

**Comment by kcbraunschweig** [comment]
Not always. tailor/lib/tailor/rulers/allow_invalid_ruby_ruler.rb does this:
`18      def invalid_ruby?
19        log "Checking for valid Ruby..."
20        result = `ruby -c #{@file_name}``

**Comment by turboladen** [comment]
Oooh, right!  Yeah, that's definitely a problem.  Thanks for the clarification!

**Comment by jaymzh** [comment]
To be more clear, you want `Gem.ruby` to get the full path to the ruby you were called in, and yes, as KC pointed out, it's in `allow_invalid_ruby_ruler.rb`
