### ISSUE TITLE
camelCaseMethods are accepted inside a class

### ISSUE THREAD

**Issue by ureczky** [turboladen/tailor#121]
CamelCase methods are accepted by tailor within a class, while outside a class, they arent.

minimal Example:

``` Ruby
def thisMethodCausesCamelCaseWarning
end

class ExampleClass
  def thisMethodDoesntCauseCamelCaseWarning
  end
end
```

I get the warning message just for the first one:

```
# Problems:
#  1.
#    * position:  1:4
#    * property:  allow_camel_case_methods
#    * message:   Camel-case method name found.
```

I have tailor 1.1.2

Other inspections (what i tried) are working inside the class, but this isnt.

My .tailor file look like this:

```
# ...
Tailor.config do |config|
  config.formatters "text"
  config.file_set './**/*.rb' do |style|
    style.allow_camel_case_methods false, level: :error
    ...
  end
end
```

**Comment by turboladen** [comment]
Whoa, that's definitely wrong!

**Comment by jasonku** [comment]
@turboladen I submitted https://github.com/turboladen/tailor/pull/125 to address this issue- could you take a look?

**Comment by turboladen** [comment]
I'm going to check into those failing travis tests before closing this.  If those are a fluke, then I'll look to doing a release with this fix in it soon.  If not, i'll need to fix those up first.

Thanks again @jasonku for that request.

**Comment by turboladen** [comment]
Fixed with gh-125.
