### ISSUE TITLE
Odd behavior with a heredoc followed by braces-with-spaces

### ISSUE THREAD

**Issue by miketheman** [turboladen/tailor#124]
Given the following `foo.rb`:

``` ruby
def some_cmd
  if true
    <<-SOME_CMD.gsub(/ {10}/, '')
      #{something.join}
    SOME_CMD
    state = "pass"
  else
    <<-SOME_CMD.gsub(/ {10}/, '')
      #{something.map {}.join}
    SOME_CMD
    state = "fail"
  end
end
```

I get:

``` console
# Problems:
#  1.
#    * position:  8:23
#    * property:  spaces_after_lbrace
#    * message:   Line has 0 space(s) after a {, but should have 1.
```

So:
A heredoc opener followed by a method that includes braces in a gsub AND followed by a string interpolation containing spaces triggers this.

Pretty odd, for sure.

**Comment by turboladen** [comment]
Man, you're finding all kinds of good ones!  I swear I'll be getting to
these at some point...

On Jan 21, 2013, at 18:16, Mike Fiedler notifications@github.com wrote:

Given the following foo.rb:

def some_cmd
  if true
    <<-SOME_CMD.gsub(/ {10}/, '')      #{something.join}    SOME_CMD
    state = "pass"
  else
    <<-SOME_CMD.gsub(/ {10}/, '')      #{something.map {}.join}    SOME_CMD
    state = "fail"
  endend

I get:

# Problems:#  1.#    \* position:  8:23#    \* property:

spaces_after_lbrace#    \* message:   Line has 0 space(s) after a {,
but should have 1.

So:
A heredoc opener followed by a method that includes braces in a gsub AND
followed by a string interpolation containing spaces triggers this.

Pretty odd, for sure.

—
Reply to this email directly or view it on
GitHubhttps://github.com/turboladen/tailor/issues/124.

**Comment by miketheman** [comment]
BTW - reconfirmed this is still an issue with 1.2.1

**Comment by miketheman** [comment]
Closing old issue, can't repro very well.
