### ISSUE TITLE
Can Tailor skip non-ruby files?

### ISSUE THREAD

**Issue by leandronsp** [turboladen/tailor#132]
I pointed a Rails app path on Tailor::CLI.new and he is trying to parse non-ruby files, like "rails.png".
And, of course, I got encoding error. 

In my branch I put a new line on method "check_style" from class Critic, just returning if the extension is not .rb

.critic.rb

``` ruby
def check_file(file, style)
  return if File.extname(file) != '.rb'
```

Would you agree with this?

**Comment by erdeszt** [comment]
This way you would skip Rakefile too, which is a ruby file and should be checked too.
I think you should use: 

``` ruby
Tailor.config.file_set '**/*.rb' ...
```

**Comment by leandronsp** [comment]
I aggree!

But this doesn't work for me:

``` ruby
Tailor.config.file_set '**/*.rb'
Tailor::CLI.new([path_to_rails_app]).result
```

neither this:

``` ruby
Tailor.config { |config| config.file_set '**/*.rb' }
Tailor::CLI.new([path_to_rails_app]).result
```

My .tailor file also is configured with:

``` code
config.recursive_file_set '*.rb'
```

But it is always getting .md, .png, .ico, .etc...
May I'm doing it wrong?

**Comment by erdeszt** [comment]
How do you pass the path to the constructor? You should do it this way:

``` ruby
Tailor::CLI.new(Dir['**/*.rb'])
```

**Comment by leandronsp** [comment]
This way it works @erdeszt. Thanks!

``` ruby
Tailor::CLI.new(Dir['other_rails_app/**/*.rb'])
```
