### ISSUE TITLE
Improper nesting detection

### ISSUE THREAD

**Issue by jaymzh** [turboladen/tailor#93]
I have code that does:

```
%w{
  foo
  bar
  baz
}.each do |thing|
  function thing do
    ...
  end
end
```

and it tells me the "function" line should be un-indented, but it's nested, so that's not right.

**Comment by turboladen** [comment]
Nice find! I need as much test code that reflects a problem at its simplest form as possible.  I'll get this in to 1.0.0 for sure. There are a couple other outstanding indentation cases as well that I plan on getting in.

**Comment by jaymzh** [comment]
Er, so I misread the message. It actually wants `function` indented to 4 instead of 2 (and the stuff inside of it to 6 instead of 4) which I don't understand at all...

**Comment by turboladen** [comment]
Hmm... I just ran it against this and don't get any errors...

```
%w{
  foo
  bar
  baz
}.each do |thing|
  function thing do
    puts "stuff"
  end 
end
```

When was the last time you pulled down the source?

Also, if that error message is confusing, what do you think is a better way to describe what tailor found vs. what it expected?

**Comment by jaymzh** [comment]
This morning...

**Comment by jaymzh** [comment]
Ohhhh.

In the stanza above it there was an

"end end"

which was wrong, but it didn't catch that, it complained about all the indentation thereafter.

**Comment by turboladen** [comment]
Ah yeah, weird stuff happens when syntax is wonky (i.e. extra 'end's).  I'll add a check to verify that the contains valid Ruby.

**Comment by jaymzh** [comment]
Actually, the number of 'end's was correct, but two of them were on the same line instead of no two separate lines...

**Comment by turboladen** [comment]
I know this isn't part of the problem that was reported, but since I mentioned it... Detection and warning of invalid Ruby was added in 45061f8f90db1c60d12e7515d77ab665c0fd90ac.
