### ISSUE TITLE
Support for another indentation type

### ISSUE THREAD

**Issue by jaymzh** [turboladen/tailor#94]
I'd like to support this style indentation

```
bla = something::somethingelse::someclass::method(foo, bar, baz,
                                                                                                bing, ding)
```

Where we indent to the opening paryn...

**Comment by jaymzh** [comment]
ack. The github markdown doesn't do waht I want. The 'bing' there should be aligned with the foo.

**Comment by jaymzh** [comment]
relatedly, I _think_ it's standard to do continuation indentation at twice that of normal indentation. So:

```
if ...
  bar
end
```

vs

```
somemethodhere(
    "long string that won't fit on above line")
```

Or better yet:

```
def something(waka, baka, bing
    bla, goop, foop)
  stuff
end
```

so they don't conflict. Of course, I'd rather the above be

```
def something(waka, baka, bing
              bla, goop, foop)
  stuff
end
```

**Comment by turboladen** [comment]
Yeah, totally.  I definitely don't like the idea of roping everyone into one style option.  Great call.
